import { makeStyles } from "@material-ui/core/styles";

export const useMediaSimpleCardStyles = makeStyles(theme => ({
  container: {
    background: "white",
    borderRadius: 14,
    position: "relative",
    overflowX: "hidden",
    boxShadow: "0px 30px 35px -12px rgba(0, 0, 0, 0.03)",
    paddingBottom: "24px",
  },
  podImageContent: {
    height: "170px",
    borderRadius: `${14}px ${14}px 0px 0px`,
    position: "absolute",
    top: 0,
    right: 0,
    left: 0,
  },
  podImage: {
    width: "100%",
    height: "100%",
    borderRadius: `${14}px ${14}px 0px 0px`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  releaseBox: {
    color: "white",
    borderRadius: theme.spacing(4),
    padding: `${theme.spacing(1)}px ${theme.spacing(2)}px`,
    fontSize: "11px",
    top: theme.spacing(3),
    left: theme.spacing(4),
    position: "absolute",
    fontFamily: "Montserrat",
  },
  title: {
    fontSize: "18px",
    fontWeight: 800,
    textOverflow: "ellipsis",
    overflowX: "hidden",
    color: "#081831",
    fontFamily: "Montserrat",
  },
  flexBox: {
    display: "flex",
    alignItems: "center",
  },
  header1: {
    fontSize: "14px",
    color: "#707582",
    fontFamily: "Montserrat",
  },
  header2: {
    color: "#707582",
    fontFamily: "Montserrat",
    fontSize: "16px",
    fontWeight: 500,
  },
  header3: {
    fontSize: "14px",
    fontFamily: "Montserrat",
    fontWeight: 800,
    color: "#181818",
  },
  button: {
    background: "#181818",
    border: "1.5px solid #181818",
    boxSizing: "border-box",
    backdropFilter: "blur(10px)",
    borderRadius: "30px",
    padding: "9.5px 50px",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "16px",
    lineHeight: "21px",
    right: 0,
  },
  contentBox: {
    paddingBottom: "22px",
    marginBottom: "20px",
    borderBottom: "1px dashed #1717173a",
    display: "flex",
    width: "100%",
    justifyContent: "space-between",
  },
  address: {
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    fontFamily: "Agrandir",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "14px",
    lineHeight: "120%",
    color: "#181818",
    "& svg": {
      marginLeft: "12px",
    },
  },
  hashtagsBox: {
    borderRadius: theme.spacing(4),
    padding: `${theme.spacing(1)}px ${theme.spacing(2)}px`,
    top: theme.spacing(3),
    right: theme.spacing(2),
    position: "absolute",
    display: "flex",
    alignItems: "center",
  },
  hashtag: {
    background: "rgba(255, 255, 255, 0.5)",
    backdropFilter: "blur(24px)",
    borderRadius: "6px",
    padding: "5px 12px 4px",
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "12px",
    lineHeight: "104.5%",
    textTransform: "uppercase",
    color: "#181818",
    "&:not(:first-child)": {
      marginLeft: 8,
    },
  },
}));
