import { makeStyles } from "@material-ui/core/styles";

export const subPageStyles = makeStyles(theme => ({
  page: {
    width: "100%",
    height: "100%",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    minHeight: "calc(100vh - 80px)",
    maxHeight: "calc(100vh - 80px)",
    overflowX: "hidden",
    position: "relative",
    [theme.breakpoints.down("sm")]: {
      "@media (max-width: 768px)": {
        minHeight: "calc(100vh - 80px - 45px)",
        maxHeight: "calc(100vh - 80px - 45px)",
      },
    },

    // [theme.breakpoints.down("xs")]: {
    //   minHeight: "calc(100vh - 80px - 55px)",
    //   maxHeight: "calc(100vh - 80px - 55px)",
    // },
  },
  content: {
    width: "100%",
    padding: "45px 80px",
    display: "flex",
    flexDirection: "column",
    height: "fit-content",
    [theme.breakpoints.down("sm")]: {
      padding: "16px 12px",
    },
  },
  headerTitle: {
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: 40,
    lineHeight: "104.5%",
    marginBottom: 40,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    color: "#181818",
    "& button": {
      marginLeft: 26,
      background: "transparent",
      padding: 0,
      borderRadius: 0,
    },
    "& button img": {
      width: 16,
      height: 18,
    },

    [theme.breakpoints.down("sm")]: {
      fontSize: 30,
      "& button": {
        marginLeft: 8,
      },
    },
    [theme.breakpoints.down("xs")]: {
      fontSize: 20,
      flexDirection: "column",
      gridRowGap: 15,
    },
  },
  marketButtonBox: {
    display: "flex",
    alignItems: "center",

    [theme.breakpoints.down("xs")]: {
      marginTop: theme.spacing(2),
    },
  },
  searcher: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 0px 12px 16px",
    flex: 1,
    maxWidth: 591,
    border: "1px solid #181818",
    boxSizing: "border-box",
    borderRadius: 6,
    marginLeft: 40,
    "& input": {
      fontStyle: "normal",
      fontWeight: 400,
      fontSize: 22,
      height: 22,
      lineHeight: "104.5%",
      color: "#181818",
      border: "none",
      padding: 0,
      outline: "none",
      width: "100%",
      borderRadius: "inherit",
      background: "transparent",
      [theme.breakpoints.down("sm")]: {
        fontSize: 16,
      },
    },
    "& input::placeholder": {
      color: "#181818",
    },
    "& img": {
      width: 28,
      [theme.breakpoints.down("sm")]: {
        width: 24,
      },
    },
    [theme.breakpoints.down(1024)]: {
      marginLeft: 0,
      marginTop: 20,
    },
    [theme.breakpoints.down("sm")]: {
      padding: "16px 0px 16px 16px",
      width: "100%",
    },
  },
  tab: {
    marginRight: 24,
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: 18,
    lineHeight: "104.5%",
    color: "#707582",
    opacity: 0.5,
    cursor: "pointer",
    [theme.breakpoints.down("xs")]: {
      fontSize: 16,
      marginRight: 18,
    },
  },
  selectedTab: {
    color: "#181818",
    opacity: 1,
  },
  artCards: {
    width: "calc(100% + 20px)",
    marginLeft: -10,
    marginTop: -10,
    marginBottom: 38,
    padding: "10px 5px",
    "& > div": {
      width: "100%",
      "& > div > div > div": {
        padding: "0 !important",
      },
    },
  },
  artistCards: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "calc(100% + 20px)",
    marginLeft: -10,
    marginTop: -10,
    marginBottom: 38,
    flexWrap: "wrap",
    overflow: "hidden",
    padding: "10px 5px",
    minHeight: 388,
    "& > div": {
      width: "100%",
    },
    [theme.breakpoints.down("sm")]: {
      width: "100%",
      marginLeft: 0,
    },
  },
  collectionCards: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "calc(100% + 20px)",
    marginLeft: -10,
    marginTop: -10,
    marginBottom: 38,
    flexWrap: "wrap",
    overflow: "hidden",
    padding: "10px 5px",
    minHeight: 300,
    "& > div": {
      width: "100%",
    },
    [theme.breakpoints.down("sm")]: {
      width: "100%",
      marginLeft: 0,
    },
  },
  empty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
    textAlign: "center",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: 18,
    lineHeight: "104.5%",
  },
  paper: {
    minWidth: 163,
    marginLeft: -15,
    borderRadius: 0,
    marginTop: 5,
    boxShadow: "0px 2px 8px rgba(0, 0, 0, 0.12)",
    [theme.breakpoints.down("sm")]: {
      marginLeft: -150,
    },
  },
  title: {
    display: "flex",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: 18,
    lineHeight: "104.5%",
    color: "#000000",
    marginBottom: 20,
    width: "100%",
    justifyContent: "space-between",
    "& span": {
      fontStyle: "normal",
      fontWeight: 800,
      fontSize: 11,
      color: "#707582",
      cursor: "pointer",
    },
  },
  viewMore: {
    fontStyle: "normal",
    fontWeight: 800,
    fontSize: 14,
    color: "#707582",
    cursor: "pointer",
  },
  artistCardsHide: {
    maxHeight: 388,
    overflow: "hidden",
  },
  collectionCardsHide: {
    maxHeight: 325,
    overflow: "hidden",
  },
  nftActionButton: {
    width: "167px !important",
    height: "40px !important",
    background: "#431AB7 !important",
    borderRadius: "6px !important",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontSize: "16px !important",
    fontWeight: 800,
    marginLeft: "16px !important",
    [theme.breakpoints.down("md")]: {
      marginLeft: "8px !important",
      width: "120px !important",
    },
  },
  filters: {
    [theme.breakpoints.down(1024)]: {
      flexDirection: "column",
      alignItems: "flex-start",
    },
  },
  collectionBack: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    height: 280,
    backgroundColor: "#9EACF2",
    borderRadius: 16,
    overflow: "hidden",
    marginTop: 30,
    marginBottom: 40,
    paddingLeft: 50,
    paddingRight: 50,
    filter: "drop-shadow(0px 0px 16px #DDFF57)",
    [theme.breakpoints.down(1200)]: {
      height: 200,
      paddingLeft: 32,
      paddingright: 32,
    },
    [theme.breakpoints.down(760)]: {
      paddingLeft: 12,
      paddingright: 12,
      height: 120,
    },
  },
  collectionImage: {
    width: "360px",
    height: "90%",
    borderRadius: 8,
    objectFit: "cover",
    [theme.breakpoints.down(1200)]: {
      width: "250px",
    },
    [theme.breakpoints.down(760)]: {
      width: "120px",
    },
  },
  collectionName: {
    color: "#431AB7",
    textShadow: "0px 4px 8px #DDFF57",
    fontSize: 72,
    marginBottom: 8,
    [theme.breakpoints.down(1200)]: {
      fontSize: 48,
    },
    [theme.breakpoints.down(760)]: {
      fontSize: 32,
    },
  },
}));
