export const SET_SELECTED_PROFILE_PAGE = "SET_SELECTED_PROFILE_PAGE";
export const SET_SELECTED_OTHER_PROFILE_PAGE = "SET_SELECTED_PROFILE_PAGE";
export const SET_SELECTED_LENDING_PAGE = "SET_SELECTED_LENDING_PAGE";
export const SET_SELECTED_USER = "SET_SELECTED_USER";
export const SET_SELECTED_AUTH_PAGE = "SET_SELECTED_AUTH_PAGE";
export const SET_UPDATE_BASIC_INFO = "SET_UPDATE_BASIC_INFO";
export const SET_UPDATE_ALL_PROFILE_INFO = "SET_UPDATE_ALL_PROFILE_INFO";
export const SET_UPDATE_DISCORD_ROOM_INFO = "SET_UPDATE_DISCORD_ROOM_INFO";
export const SET_UPDATE_POD_CREATION = "SET_UPDATE_POD_CREATION";
export const SET_SIDE_BAR_SHOW = "SET_SIDE_BAR_SHOW";
export const SET_SELECTED_MENU_PRIVI_SWAP = "SET_SELECTED_MENU_PRIVI_SWAP";
export const SET_SELECTED_SWAP_TABS_VALUE = "SET_SELECTED_SWAP_TABS_VALUE";
export const SET_SELECTED_SWAP_TAB_POOL = "SET_SELECTED_SWAP_TAB_POOL";
export const SET_SELECTED_LIQUIDITY_POOL_PRIVI_SWAP =
  "SET_SELECTED_LIQUIDITY_POOL_PRIVI_SWAP";
export const SET_SELECTED_TOKEN_PRIVI_SWAP = "SET_SELECTED_TOKEN_PRIVI_SWAP";
export const SET_SELECTED_PROTECTION_OPTIONS_SWAP =
  "SET_SELECTED_PROTECTION_OPTIONS_SWAP";

// USER
export const SET_USER = "SET_USER";
export const EDIT_USER = "EDIT_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const SIGN_OUT = "SIGN_OUT";
export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";
export const SET_ETH_ACCOUNT = "SET_ETH_ACCOUNT";
export const SET_ETH_BALANCE = "SET_ETH_BALANCE";
export const SET_FAB_BALANCE = "SET_FAB_BALANCE";
export const SET_ETH_EXTERNAL_WALLET = "SET_ETH_EXTERNAL_WALLET";
export const SET_WEB3 = "SET_WEB3";
export const SET_LOGIN_BOOL = "SET_LOGIN_BOOL";

export const SET_AVAILABLE_TOKENS = "SET_AVAILABLE_TOKENS";

export const SET_USERS_INFO_LIST = "SET_USERS_INFO_LIST";

export const UPDATE_ANON_AVATAR = "UPDATE_ANON_AVATAR";
export const UPDATE_TUTORIALS_SEEN = "UPDATE_TUTORIALS_SEEN";
export const UPDATE_PROFILE_BACKGROUND = "UPDATE_PROFILE_BACKGROUND";

export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const UPDATE_WALLET_ADDRESS = "UPDATE_WALLET_ADDRESS";

// USER BALANCES
export const SET_USER_BALANCES = "SET_USER_BALANCES";
export const SET_USER_BALANCE = "SET_USER_BALANCE";

// LENDINGS
export const SET_PRIVI_LENDING = "SET_PRIVI_LENDING";
export const SET_ALL_PRIVI_LENDING = "SET_ALL_PRIVI_LENDING";
export const REMOVE_PRIVI_LENDING = "REMOVE_PRIVI_LENDING";
export const SET_LOAN = "SET_LOAN";
export const REMOVE_LOAN = "REMOVE_LOAN";
export const SET_ALL_LOAN = "SET_ALL_LOAN";
export const SET_RESERVE = "SET_RESERVE";
export const SET_ALL_RESERVE = "SET_ALL_RESERVE";
export const REMOVE_RESERVE = "REMOVE_RESERVE";

// PODS MANAGER
export const SET_MY_PODS_LIST = "SET_MY_PODS_LIST";
export const SET_TRENDING_PODS_LIST = "SET_TRENDING_PODS_LIST";
export const SET_OTHER_PODS_LIST = "SET_OTHER_PODS_LIST";
export const SET_MY_PODS_LOADING = "SET_MY_PODS_LOADING";
export const SET_TRENDING_PODS_LOADING = "SET_TRENDING_PODS_LOADING";
export const SET_OTHER_PODS_LOADING = "SET_OTHER_PODS_LOADING";
export const SET_POD_MENU_SELECTION = "SET_POD_MENU_SELECTION";

// STAKING
export const SET_STAKING = "SET_STAKING";
export const SET_ALL_STAKING = "SET_ALL_STAKING";
export const REMOVE_STAKING = "REMOVE_STAKING";

// TRANSACTIONS
export const SET_TRANSACTIONS_LIST = "SET_TRANSACTIONS_LIST";

// POOLS MANAGER
export const SET_TRENDING_POOLS_LIST = "SET_TRENDING_POOLS_LIST";
export const SET_POOLS_LIST = "SET_POOLS_LIST";
export const SET_TRENDING_POOLS_LOADING = "SET_TRENDING_POOLS_LOADING";
export const SET_POOLS_LOADING = "SET_POOLS_LOADING";

export const SET_SELECTED_DISCORD_ROOM = "SET_SELECTED_DISCORD_ROOM";
export const SET_USERS_DISCORD_ROOM = "SET_POOLS_LOADING";
export const SET_USERS_TYPES_DISCORD_ROOM = "SET_POOLS_LOADING";

export const SET_UPDATE_SLUG = "SET_UPDATE_SLUG";
