import { makeStyles } from "@material-ui/core/styles";

export const fractionalizedNFTCardStyles = makeStyles(theme => ({
  card: {
    background: "#ffffff",
    boxShadow: "0px 4px 8px #9EACF2",
    borderRadius: 21,
    minWidth: 276,
    height: "fit-content",
    padding: '32px 21px 16px',
  },
  header: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    justifyContent: "space-between",
    "& button": {
      background: "transparent",
      padding: 0,
      borderRadius: 0,
      marginLeft: 12,
    },
    "& button img": {
      width: 18,
    },
  },
  avatar: {
    backgroundColor: "#c4c4c4",
    width: 54,
    minWidth: 54,
    height: 54,
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
    backgroundPosition: "center",
    marginRight: 10,
  },
  black: {
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: 18,
    lineHeight: "120%",
    fontFamily: 'Agrandir',
    color: "#1a1b1c",
  },
  creatorName: {
    maxWidth: 124,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    lineHeight: 1.2,
  },
  gray: {
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: 18,
    lineHeight: "120%",
    color: "#a4a4a4",
    fontFamily: 'Agrandir',
    overflow: "hidden",
    "& span": {
      fontStyle: "normal",
      fontWeight: 800,
      fontSize: 18,
      lineHeight: "104.5%",
      color: "#431ab7",
      marginLeft: 8,
    },
  },
  optionsBtn: {
    width: 18,
  },
  media: {
    width: "100%",
    margin: "16px 0px",
    borderRadius: 16,
    height: "auto",
    minHeight: 226,
  },
  fixed: {
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundColor: "#c4c4c4",
    height: 226,
    maxHeight: 226,
  },
  info: {
    display: "flex",
    flexDirection: "column",
    "& > div": {
      marginBottom: 8,
      width: "100%",
      textOverflow: "ellipsis",
      overflow: "hidden",
      whiteSpace: "nowrap",
    },
    "& > div:last-child": {
      marginBottom: 8,
    },
    cursor: "pointer",
  },
  title: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: "250px",
  },
  chain: {
    width: 25,
    height: 16,
    objectFit: "contain",
    borderRadius: "50%",
  },
  fraction: {
    background: "#431AB7",
    borderRadius: 24,
    color: "#DDFF57",
    fontSize: 12,
    fontWeight: 800,
    padding: 8,
  },
  podMainInfoContent: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    cursor: "pointer",
    fontFamily: 'Agrandir',
    "& div": {
      display: "flex",
      flexDirection: "column",
      "& span": {
        fontSize: 12,
        fontWeight: 400,
        color: '#707582'
      },
      "& p": {
        fontSize: 18,
        fontWeight: 800,
        color: "#431AB7",
      },
    },
  },
  viewsBox: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderTop: "1px solid #00000022",
    borderBottom: "1px solid #00000022",
    marginBottom: 16,
    cursor: "pointer"
  },
  liveSaleBtn: {
    display: "flex",
    height: 27,
    padding: "7px 11px",
    color: "#431AB7",
    fontSize: 10,
    fontWeight: 800,
    fontFamily: "Agrandir",
    lineHeight: "18px",
    background: "#DDFF57",
    borderRadius: 6.8,
    width: 80,
    position: 'absolute',
    top: 8,
    right: 7,
    "& span": {
      marginLeft: 5.7,
      whiteSpace: "nowrap"
    },
  },
  liveAuctionBtn: {
    display: "flex",
    height: 27,
    padding: "5px 11px",
    color: "#431AB7",
    fontSize: 10,
    fontWeight: 800,
    fontFamily: "Agrandir",
    lineHeight: "18px",
    background: "#EFF2FD",
    borderRadius: 6.8,
    border: "1px solid #431AB7",
    width: 96,
    position: 'absolute',
    top: 8,
    right: 7,
    "& span": {
      marginLeft: 5.7,
      whiteSpace: "nowrap"
    },
  },
  closedBtn: {
    display: "flex",
    alignItems: "center",
    height: 27,
    padding: "7px 11px",
    color: "#F2604C",
    fontSize: 10,
    fontWeight: 800,
    fontFamily: "Agrandir",
    lineHeight: "18px",
    background: "#EFF2FD",
    borderRadius: 6.8,
    border: "1px solid #F2604C",
    width: 72,
    position: 'absolute',
    top: 8,
    right: 7,
    "& span": {
      marginLeft: 5.7,
      whiteSpace: "nowrap"
    },
  },
  auctionSection: {
    display: "flex",
    flexDirection: "column",
    padding: "8px 16px",
    position: "static",
    width: "100%",
    background: "#ddff57",
    borderRadius: 8,
    margin: "0px 0px 16px",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: 14,
    lineHeight: "120%",
    color: "#431ab7",
    "& span": {
      fontStyle: "normal",
      fontWeight: 800,
      fontSize: 18,
      lineHeight: "104.5%",
      color: "#431ab7",
      margin: "8px 0px 0px",
    },
  },
}));
