import { makeStyles, createStyles, Theme } from "@material-ui/core";

export const airdropTokensModalStyles = makeStyles((theme: Theme) =>
  createStyles({
    root: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
    },
    modalContent: {
      backgroundColor: "#ffffff",
      padding: "25px 30px",
      borderRadius: 16,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "space-between",
      width: 535,
      maxWidth: "calc(85vw - 50px)",
      outline: "none",
      maxHeight: "calc(85vh - 50px)",
      overflowY: "auto",
      scrollbarWidth: "none",
      position: "relative",
    },
    exitImg: {
      position: "absolute",
      top: 25,
      right: 25,
      width: 15,
      cursor: "pointer",
    },
    mainContent: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "space-between",
      height: "100%",
      width: "100%",
      marginBottom: 16,
      "& h3": {
        fontStyle: "normal",
        fontWeight: 400,
        fontSize: 30,
        textAlign: "center",
        margin: 0,
      },
    },
    logoImg: {
      width: 50,
      height: 50,
      marginTop: 40,
      marginBottom: 32,
    },
    contentDescription: {
      fontSize: 18,
      fontWeight: 400,
      color: "#707582",
    },
    shareSection: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      width: "100%",
      margin: "20px 0 30px",
      "& label": {
        fontSize: 18,
        fontWeight: 400,
        marginBottom: 12,
      },
    },
    inputContainer: {
      marginTop: 10.5,
      border: "1px solid #949bab",
      boxSizing: "border-box",
      borderRadius: 11.36,
      fontStyle: "normal",
      fontWeight: 400,
      fontSize: 14,
      lineHeight: "120%",
      color: "#181818",
      padding: "18.5px 18px",
      width: "100%",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      "& input": {
        padding: 0,
        fontFamily: "Agrandir",
        width: 300,
      },
      "& img": {
        width: 17,
        height: 17,
      },
    },
    disabledInput: {
      background: "#e6e4e470",
    },
    walletAddress: {
      flexGrow: 1,
      border: "none",
      textOverflow: "ellipsis",
      outline: "none",
    },
    tokenAmount: {
      flexGrow: 1,
      border: "none",
      textOverflow: "ellipsis",
      outline: "none",
      width: "calc(100% - 10px)",
      height: 30,
      fontSize: 16,
    },
    userImage: {
      width: 30,
      height: 30,
      minWidth: 30,
      borderRadius: 15,
      backgroundColor: "#656e7e",
      marginRight: 10,
    },
    usersDisplay: {
      display: "flex",
      flexWrap: "wrap",
      width: "100%",
      marginTop: 25,
      marginBottom: 30,
      padding: "0px 10px",
      overflowY: "auto",
      scrollbarWidth: "none",
      "& > div": {
        display: "flex",
        justifyContent: "space-between",
        width: "100%",
        alignItems: "center",
        borderBottom: "1px solid #eff2f8",
        padding: "12px 0px",
        height: "60px",
        "& span": {
          marginLeft: 5,
          display: "flex",
          alignItems: "center",
          "& img": {
            cursor: "pointer",
            height: 17,
            width: 16,
          },
        },
      },
    },
    leftSideSection: {
      display: "flex",
      alignItems: "center",
    },
    avatarSection: {
      width: 34,
      height: 34,
      minWidth: 34,
      borderRadius: "50%",
      marginRight: 12,
      filter: "drop-shadow(0px 2px 8px rgba(0, 0, 0, 0.12))",
      border: "3px solid #ffffff",
      backgroundColor: "white",
    },
    userInfoSection: {
      display: "flex",
      fontSize: 14,
      color: "#181818",
    },
    nameSection: {
      fontWeight: "bold",
      marginRight: 8,
    },
    step2Header: {
      textAlign: "left",
      color: "#181818",
      width: "100%",
      "& h3": {
        fontWeight: 800,
        fontSize: 22,
        marginTop: 40,
        marginBottom: 32,
      },
      "& h4": {
        fontWeight: 800,
        fontSize: 18,
        color: "#000000",
        margin: 0,
      },
      "& p": {
        color: "#707582",
        fontSize: 14,
        margin: 0,
        marginBottom: 35,
      },
    },
    step2UserAmount: {
      borderBottom: "1px solid #eff2f8",
      marginBottom: 20,
      width: "100%",
    },
    step2Title: {
      fontSize: 16,
      color: "#181818",
      height: 35,
    },
    userTKNSection: {
      fontSize: 16,
      color: "#181818",
    },
    controlButtons: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      width: "100%",
    },
    button: {
      fontWeight: 800,
      fontSize: 16,
      height: 40,
      padding: "9px 25px",
      borderadius: 6,
      "&:last-child": {
        marginLeft: 8,
      },
    },
    amountInputContainer: {
      border: "1px solid #949bab",
      borderRadius: 11.36,
      color: "#181818",
      padding: "11.5px 12px",
    },
  })
);

export const useAutoCompleteStyles = makeStyles({
  root: {
    width: "100%",
  },
  listbox: {
    maxHeight: 168,
  },
  option: {
    height: 52,
  },
});
