import { makeStyles } from "@material-ui/core/styles";

export const createImportSocialTokenModalStyles = makeStyles(() => ({
  root: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  tokenModalContent: {
    backgroundColor: "white",
    padding: 40,
    width: 892,
    maxWidth: "85vw",
    maxHeight: "85vh",
    borderRadius: 16,
    overflow: "auto",
    display: "flex",
    flexDirection: "column",
  },
  closeButton: {
    justifySelf: "flex-end",
    alignSelf: "flex-end",
    cursor: "pointer",
  },
  optionButtonSection: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    marginBottom: 16,
  },
  optionButton: {
    display: "flex",
    alignItems: "center",
    alignSelf: "center",
    order: 1,
    color: "#ffffff",
    borderColor: "#000000",
    background: "#000000",
    marginLeft: 20,
  },
  selectedOptionButton: {
    fontFamily: "Agrandir",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "22px !important",
    border: "none !important",
    lineHeight: "1.1 !important",
    backgroundColor: "transparent !important",
    borderColor: "transparent !important",
    color: "#000000 !important",
    height: "auto",
    padding: "0 !important",
    margin: "0 !important",
    order: 0,
  },
  tokenAssistanceSection: {
    display: "flex",
    alignItems: "center",
    marginLeft: 20,
    "& h4": {
      display: "flex",
      whiteSpace: "nowrap",
      alignItems: "center",
    },
  },
  tooltipHeaderInfo: {
    verticalAlign: "top",
    marginLeft: 2,
    width: 14,
    height: 14,
    transform: "translateY(-5px)",
  },
  optionButtonsAssistance: {
    marginLeft: 20,
  },
  tokenAssistanceNotRequiredSelected: {
    borderRadius: "50%",
    background: "black",
  },
  tokenAssistanceNotRequired: {
    width: 34,
    backgroundColor: "transparent",
    border: "none",
    color: "#ffffff",
    height: 34,
    margin: "3px 0px 3px 3px",
    padding: 0,
    borderRadius: "50%",
    cursor: "pointer",
  },
  tokenAssistanceRequiredSelected: {
    borderRadius: "50%",
    background: "linear-gradient(97.4deg, #29e8dc 14.43%, #03eaa5 79.45%)",
  },
  tokenAssistanceRequired: {
    width: 34,
    backgroundColor: "transparent",
    color: "#ffffff",
    height: 34,
    margin: "3px 3px 3px 0px",
    padding: 0,
    borderRadius: "50%",
    cursor: "pointer",
    border: "none",
  },
  mainContent: {
    width: "100%",
  },
  inputSection: {
    display: "flex",
    width: "100%",
  },
  infoHeaderTitle: {
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: 18,
    color: "#181818",
  },
  infoInputSection: {
    width: "100%",
    height: 46,
    backgroundColor: "rgba(227, 233, 239, 0.3)",
    borderRadius: 8,
    border: "1px solid #E0E4F3",
    marginTop: 8,
    color: "rgb(101, 110, 126)",
    fontSize: 14,
    fontWeight: 400,
    paddingLeft: 20,
    marginBottom: 19,
    outline: "none",
    "& ::placeholder": {
      color: "rgba(101, 110, 126, 0.5)",
      fontSize: 14,
      fontWeight: 400,
    },
  },
  infoInputTextAreaSection: {
    width: "100%",
    "-webkit-box-sizing": "border-box",
    height: 238,
    margin: "8px 0",
    padding: 16,
    border: "1px solid #e0e4f3",
    borderRadius: 8,
    "& ::placeholder": {
      color: "rgba(101, 110, 126, 0.5)",
      fontSize: 14,
      fontWeight: 400,
    },
  },
  imageCreateSection: {
    marginTop: 8,
    background: "#f7f9fe",
    border: "1px dashed #e0e4f3",
    boxSizing: "border-box",
    borderRadius: 8,
    marginRight: 0,
    width: "100%",
    height: 340,
  },
  removeImageButton: {
    right: 10,
  },
  dragImageHereCreateSection: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    marginTop: 8,
    background: "#f7f9fe",
    border: "1px dashed #e0e4f3",
    boxSizing: "border-box",
    borderRadius: 8,
    marginRight: 0,
    width: "100%",
    height: 239,
    cursor: "pointer",
  },
  dragImageHereIcon: {
    width: 40,
    height: 32,
  },
  dragImageHereLabel: {
    color: "#ABB3C3",
    fontSize: 14,
    fontWeight: 400,
    fontFamily: "Agrandir",
  },
  fundingTokenSection: {
    margin: "16px 0",
  },
  fundingTokenInputSection: {
    display: "flex",
    width: "100%",
    marginBottom: 8,
  },
  customSelectSection: {
    height: 46,
    position: "relative",
    borderRadius: 8,
    border: "1px solid #E0E4F3",
    marginTop: 8,
    paddingTop: 2,
    paddingLeft: 5,
  },
  optionButtonsGroupSection: {
    display: "flex",
    alignContent: "space-between",
    alignSelf: "flex-start",
    backgroundColor: "transparent",
  },
  ammSection: {
    marginTop: 32,
    marginBottom: 8,
  },
  optionButtonsGroupSectionSelectedButton: {
    fontWeight: "bold",
    fontSize: 14,
    textAlign: "center",
    letterSpacing: "-0.02em",
    textTransform: "capitalize",
    color: "#ffffff",
    borderRadius: "32px",
    padding: "8px 26px",
    backgroundColor: "#000000",
    marginRight: 24,
  },
  optionButtonsGroupSectionButton: {
    border: "2px solid #99a1b3",
    boxSizing: "border-box",
    backgroundColor: "transparent",
    fontFamily: "Agrandir",
    fontWeight: "bold",
    fontSize: 14,
    textAlign: "center",
    letterSpacing: "-0.02em",
    textTransform: "capitalize",
    color: "#707582",
    borderRadius: "32px",
    padding: "8px 26px",
    transition: "all 0.3s",
    marginRight: 24,
  },
  loadingBar: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  createTokenButton: {
    backgroundColor: "#181818",
    borderRadius: 10,
    padding: "8px 26px",
    fontSize: 16,
    margin: 0,
    color: "white",
  },
  ammInputSection: {
    display: "flex",
    width: "100%",
    marginBottom: 8,
  },
  plotSection: {
    display: "flex",
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  createTokenButtonSection: {
    width: "100%",
    display: "flex",
    justifyContent: "flex-end",
  },
  imageSection: {
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
    cursor: "pointer",
    height: 300,
  },
}));
