import { BlockchainType, PlatformType } from "shared/services/API";

export const CollectionsWax = [
  {
    name: "alien.worlds",
    label: "Alien Worlds",
    imageURL: "alien.worlds.png",
    blockChain: BlockchainType.Wax,
    platform: PlatformType.Wax
  },
  {
    name: "ultrahorrors",
    label: "Ultra Horrors",
    imageURL: "ultrahorrors.png",
    blockChain: BlockchainType.Wax,
    platform: PlatformType.Wax
  },
  {
    name: "bitcoinorign",
    label: "Bitcoin Origin",
    imageURL: "bitcoinorign.png",
    blockChain: BlockchainType.Wax,
    platform: PlatformType.Wax
  },
  {
    name: "rplanet",
    label: "R Planet",
    imageURL: "rplanet.png",
    blockChain: BlockchainType.Wax,
    platform: PlatformType.Wax
  },
  {
    name: "upland.cards",
    label: "Upland",
    imageURL: "upland.cards.png",
    blockChain: BlockchainType.Wax,
    platform: PlatformType.Wax
  },
  {
    name: "kogsofficial",
    label: "Kogs",
    imageURL: "kogsofficial.png",
    blockChain: BlockchainType.Wax,
    platform: PlatformType.Wax
  },
  {
    name: "flegendsnfts",
    label: "F Legends",
    imageURL: "flegendsnfts.png",
    blockChain: BlockchainType.Wax,
    platform: PlatformType.Wax
  },
  {
    name: "hodlgod",
    label: "HodlGod",
    imageURL: "hodlgod.png",
    blockChain: BlockchainType.Wax,
    platform: PlatformType.Wax
  },
  {
    name: "upliftworld2",
    label: "Uplift World",
    imageURL: "upliftworld2.png",
    blockChain: BlockchainType.Wax,
    platform: PlatformType.Wax
  },
  {
    name: "stf.capcom",
    label: "Capcom",
    imageURL: "stf.capcom.png",
    blockChain: BlockchainType.Wax,
    platform: PlatformType.Wax
  },
  {
    name: "cartombs.r2",
    label: "Cartombs",
    imageURL: "cartombs.r2.png",
    blockChain: BlockchainType.Wax,
    platform: PlatformType.Wax
  },
  {
    name: "crptomonkeys",
    label: "CryptoMonkeys",
    imageURL: "crptomonkeys.png",
    blockChain: BlockchainType.Wax,
    platform: PlatformType.Wax
  },
];

export const CollectionsShowTime = [
  {
    name: "async-art",
    label: "Async Art",
    imageURL: "async-art.png",
    blockChain: BlockchainType.Eth,
    platform: PlatformType.Showtime
  },
  {
    name: "blockart",
    label: "BlockArt",
    imageURL: "block-art.png",
    blockChain: BlockchainType.Eth,
    platform: PlatformType.Showtime
  },
  {
    name: "charged-particles-proton",
    label: "Charged Particles",
    imageURL: "charged-particles-proton.png",
    blockChain: BlockchainType.Eth,
    platform: PlatformType.Showtime
  },
  {
    name: "fnd",
    label: "Foundation",
    imageURL: "fnd.png",
    blockChain: BlockchainType.Eth,
    platform: PlatformType.Showtime
  },
  {
    name: "hashmasks",
    label: "Hashmasks",
    imageURL: "hashmasks.png",
    blockChain: BlockchainType.Eth,
    platform: PlatformType.Showtime
  },
  {
    name: "known-origin",
    label: "Known Origin",
    imageURL: "known-origin.png",
    blockChain: BlockchainType.Eth,
    platform: PlatformType.Showtime
  },
  {
    name: "makersplace",
    label: "Makersplace",
    imageURL: "makersplace.png",
    blockChain: BlockchainType.Eth,
    platform: PlatformType.Showtime
  },
  {
    name: "mintable-store",
    label: "Mintable",
    imageURL: "mintable.png",
    blockChain: BlockchainType.Eth,
    platform: PlatformType.Showtime
  },
  {
    name: "portion",
    label: "Portion",
    imageURL: "portion.png",
    blockChain: BlockchainType.Eth,
    platform: PlatformType.Showtime
  },
  {
    name: "rarible",
    label: "Rarible",
    imageURL: "rarible.png",
    blockChain: BlockchainType.Eth,
    platform: PlatformType.Showtime
  },
  {
    name: "spotlights",
    label: "Spotlights",
    imageURL: "spotlights.png",
    blockChain: BlockchainType.Eth,
    platform: PlatformType.Showtime
  },
  {
    name: "superrare",
    label: "Superrare",
    imageURL: "superrare.png",
    blockChain: BlockchainType.Eth,
    platform: PlatformType.Showtime
  },
  {
    name: "zora",
    label: "Zora",
    imageURL: "zora.png",
    blockChain: BlockchainType.Eth,
    platform: PlatformType.Showtime
  },
];

export const CollectionsOpensea = [
  { name: "0n1-force", label: "0N1 Force", imageURL: "0n1-force.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "888innercircle", label: "888 inner circle", imageURL: "888innercircle.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "acclimatedmooncats", label: "Official MoonCats - Acclimated", imageURL: "acclimatedmooncats.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "ackeditions", label: "ACK EDITIONS", imageURL: "ackeditions.gif", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "adam-bomb-squad", label: "Adam Bomb Squad", imageURL: "adam-bomb-squad.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "afterorder", label: "AFTERORDER", imageURL: "afterorder.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "autoglyphs", label: "Autoglyphs", imageURL: "autoglyphs.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "axolittles", label: "Axolittles", imageURL: "axolittles.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "borpacasso", label: "Borpacasso", imageURL: "borpacasso.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "blitmap", label: "Blitmap", imageURL: "blitmap.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "blootofficial", label: "Bloot (not for Weaks)", imageURL: "blootofficial.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "bored-ape-chemistry-club", label: "Bored Ape Chemistry Club", imageURL: "bored-ape-chemistry-club.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "bored-ape-kennel-club", label: "Bored Ape Kennel Club", imageURL: "bored-ape-kennel-club.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "boredapeyachtclub", label: "Bored Ape Yacht Club", imageURL: "boredapeyachtclub.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "chibi-apes", label: "Chibi Apes", imageURL: "chibiapes.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "cool-cats-nft", label: "Cool Cats NFT", imageURL: "cool-cats-nft.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "creature-world-collection", label: "Creature World NFT", imageURL: "creature-world-collection.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "cryptoadz-by-gremplin", label: "CrypToadz by GREMPLIN", imageURL: "cryptoadzbygremplin.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "cryptocannabisclub", label: "Crypto Cannabis Club", imageURL: "cryptocannabisclub.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "crypto-pills-by-micha-klein", label: "Crypto-Pills by Micha Klein", imageURL: "crypto-pills-by-micha-klein.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "cryptopochi", label: "CryptoPochi", imageURL: "cryptopochi.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "cryptopunks", label: "CryptoPunks", imageURL: "cryptopunks.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "curiocardswrapper", label: "My Curio Cards", imageURL: "curiocardswrapper.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "cyberkongz", label: "CyberKongz", imageURL: "cyberkongz.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "cyberkongz-vx", label: "CyberKongz VX", imageURL: "cyberkongz-vx.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "decentraland", label: "Decentraland", imageURL: "decentraland.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "dotdotdots", label: "dotdotdots", imageURL: "dotdotdots.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "dgenesis-dgen-automatons", label: "dGenesis dGen Automatons", imageURL: "dgenesis-dgen-automatons.gif", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "dystopunks-v2", label: "DystoPunks V2", imageURL: "dystopunks-v2.gif", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "emblem-vault", label: "Emblem Vault [Ethereum]", imageURL: "emblemvault.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "ether-cards-founder", label: "Ether Cards Founder", imageURL: "ether-cards-founder.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "ethereans-official", label: "Ethereans Official", imageURL: "ethereans-official.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "fatales", label: "Fatales", imageURL: "fatales.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "fewmans", label: "Fewmans", imageURL: "fewmans.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "firstproject", label: "First First NFTs", imageURL: "firstproject.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "fewocious-x-rtfkt", label: "FEWOCiOUS x RTFKT", imageURL: "fewocious-x-rtfkt.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "fluf-world", label: "FLUF World", imageURL: "fluf-world.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "frontiergame", label: "Frontier Game", imageURL: "frontiergame.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "fusionape", label: "FusionApes", imageURL: "fusionape.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "galaxyeggs9999", label: "Galaxy-Eggs", imageURL: "galaxyeggs9999.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "gamblingapesofficial", label: "Gambling Apes Official", imageURL: "gamblingapesofficial.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "gen-art-collection", label: "GEN.ART Collection", imageURL: "gen-art-collection.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "gen-dot-art", label: "GEN.ART Membership", imageURL: "gen-dot-art.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "g-evols", label: "GEVOLs", imageURL: "g-evols.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "guardians-of-the-metaverse", label: "Guardians of the Metaverse", imageURL: "guardians-of-the-metaverse.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "guttercatgang", label: "Gutter Cat Gang", imageURL: "guttercatgang.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "gutter-species-mint-pass", label: "Gutter Species Mint Pass", imageURL: "gutter-species-mint-pass.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "hashmasks", label: "Hashmasks", imageURL: "hashmasks.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "heroes-of-evermore", label: "Heroes of Evermore", imageURL: "heroes-of-evermore.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "infinites-ai", label: "Infinites AI", imageURL: "infinites-ai.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "influenceth-asteroids", label: "Influenceth Asteroids", imageURL: "influenceth-asteroids.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "koala-intelligence-agency", label: "Koala Intelligence Agency", imageURL: "koala-intelligence-agency.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "lazy-lions", label: "Lazy Lions", imageURL: "lazy-lions.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "leagueofsacreddevils", label: "The League Of Sacred Devils", imageURL: "leagueofsacreddevils.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "lootproject", label: "Loot (for Adventurers)", imageURL: "lootproject.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "lostpoets", label: "LOSTPOETS", imageURL: "lostpoets.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "lysergiclabsshroomz", label: "Lysergic Labs Shroomz", imageURL: "lysergiclabsshroomz.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "makersplace", label: "Makersplace", imageURL: "makersplace.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "meebits", label: "Meebits", imageURL: "meebits.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "metahero-generative", label: "MetaHero Universe: Generative Identities", imageURL: "metahero-generative.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "monkeybet", label: "Monkey Bet DAO", imageURL: "monkeybet.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "moonpass", label: "MoonPass - The Moon Boyz", imageURL: "moonpass.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "mutant-ape-yacht-club", label: "Mutant Ape Yacht Club", imageURL: "mutant-ape-yacht-club.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  // {name: "mutantgardenseeder", label: "mutantgardenseeder", imageURL: "mutant-garden-seeder.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea},
  { name: "n-project", label: "The n project", imageURL: "n-project.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "octohedz", label: "OctoHedz", imageURL: "octohedz.gif", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "onchainmonkey", label: "OnChainMonkey", imageURL: "onchainmonkey.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "parallelalpha", label: "Parallel Alpha", imageURL: "parallelalpha.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "plasmabears", label: "Plasma Bears", imageURL: "plasma-bears.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "pudgypenguins", label: "Pudgy Penguins", imageURL: "pudgypenguins.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "punks-comic", label: "PUNKS Comic", imageURL: "punks-comic.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "purrnelopes-country-club", label: "Purrnelopes Country Club", imageURL: "purrnelopes-country-club.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "rarible", label: "Rarible", imageURL: "rarible.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "robotos-official", label: "Robotos Official", imageURL: "robotos-official.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "roguesocietybot", label: "Rogue Society Bots", imageURL: "roguesocietybot.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "roleformetaverse", label: "RoleforMetaverse(Official)", imageURL: "role-for-metaverse.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  // {name: "rookieleague", label: "rookieleague", imageURL: "rookie-league.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea},
  { name: "rtfkt-punk-project-gen1", label: "RTFKT PUNK PROJECT GEN 1", imageURL: "rtfkt-punk-project-gen1.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "rumble-kong-league", label: "Rumble Kong League", imageURL: "rumble-kong-league.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "sandbox", label: "The Sandbox", imageURL: "sandbox.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "savage-droids", label: "Savage Droids", imageURL: "savage-droids.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "sipheriansurge", label: "Sipherian Surge", imageURL: "sipheriansurge.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  // {name: "slootscammerloot", label: "slootscammerloot", imageURL: "sloot-scammer-loot.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea},
  { name: "sneaky-vampire-syndicate", label: "Sneaky Vampire Syndicate", imageURL: "sneaky-vampire-syndicate.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "sneaky-vampire-syndicate", label: "Sneaky Vampire Syndicate", imageURL: "sneaky-vampire-syndicate.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "sorare", label: "Sorare", imageURL: "sorare.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "space-dinos-club", label: "Space Dinos Club", imageURL: "space-dinos-club.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "supducks", label: "SupDucks", imageURL: "supducks.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "superrare", label: "Superrare", imageURL: "superrare.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  // {name: "sushiverseofficial", label: "sushiverseofficial", imageURL: "sushiverse-official.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea},
  { name: "sympathyforthedevils", label: "SympathyForTheDevils", imageURL: "sympathyforthedevils.gif", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "thecryptodads", label: "The CryptoDads", imageURL: "thecryptodads.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "thecurrency", label: "Damien Hirst - The Currency", imageURL: "thecurrency.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "the-doge-pound", label: "The Doge Pound", imageURL: "the-doge-pound.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "theimmortalz", label: "IMMORTALZ - Ambary Assassins", imageURL: "theimmortalz.gif", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  // {name: "theonft", label: "theonft", imageURL: "theonft.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea},
  { name: "theprojecturs", label: "The Project URS", imageURL: "theprojecturs.gif", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "the-meta-key", label: "The Meta Key", imageURL: "the-meta-key.gif", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "the-sevens-official", label: "The Sevens (Official)", imageURL: "the-sevens-official.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "tie-dye-ninjas", label: "Tie Dye Ninjas", imageURL: "tie-dye-ninjas.gif", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "tiki-bar", label: "TiKi Bar", imageURL: "tiki-bar.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  // {name: "treasureforloot", label: "treasureforloot", imageURL: "treasureforloot.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea},
  { name: "tunesproject", label: "Tunes Project", imageURL: "tunesproject.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "twinflames", label: "Twin Flames", imageURL: "twinflames.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "uwucrew", label: "uwucrew", imageURL: "uwucrew.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "veefriends", label: "VeeFriends", imageURL: "veefriends.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "vgds", label: "Video Game Dev Squad", imageURL: "vgds.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "wicked-ape-bone-club", label: "Wicked Ape Bone Club", imageURL: "wicked-ape-bone-club.png", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  { name: "wicked-hound-bone-club", label: "Wicked Hound Bone Club", imageURL: "wicked-hound-bone-club.gif", blockChain: BlockchainType.Eth, platform: PlatformType.Opensea },
  // POLYGON
  { name: "zed-run-official", label: "ZED RUN", imageURL: "zed-run-official.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "chicken-derby", label: "Chicken Derby", imageURL: "chicken-derby.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "emblem-vault-matic", label: "Emblem Vault [Polygon]", imageURL: "emblem-vault-matic.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "nftokins", label: "Crypto Cannabis Club NFTokins", imageURL: "nftokins.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "neon-district-season-one-item", label: "Neon District Season One Item", imageURL: "neon-district-season-one-item.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "revv-motorsport-inventory", label: "REVV Racing", imageURL: "revv-motorsport-inventory.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "embersword-land", label: "Ember Sword Land", imageURL: "embersword-land.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "thevisitors", label: "The Visitors", imageURL: "thevisitors.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "crypto-raiders-characters", label: "Crypto Raiders Characters", imageURL: "crypto-raiders-characters.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "hok-main", label: "HOK Main", imageURL: "hok-main.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "artvatars", label: "Artvatars", imageURL: "artvatars.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "riot-racers-gas-stations", label: "Riot Racers Gas Stations", imageURL: "riot-racers-gas-stations.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "riot-racers-cars", label: "Riot Racers Cars", imageURL: "riot-racers-cars.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "maticpunks", label: "MaticPunks", imageURL: "maticpunks.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "marblecards", label: "MarbleCards", imageURL: "marblecards.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "mycryptoheroes", label: "MyCryptoHeroes", imageURL: "mycryptoheroes.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "decentraland-wearables", label: "Decentraland Wearables", imageURL: "decentralandwearables.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "snooknft", label: "SnookNFT", imageURL: "snooknft.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "polypunk", label: "Polypunk", imageURL: "polypunk.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "ethernity-master", label: "Ethernity's Master Collection", imageURL: "ethernity-master.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "dragon-hunters", label: "Dragon Hunters", imageURL: "dragon-hunters.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "ethermon", label: "Ethermon", imageURL: "ethermon.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "zombie-racing-club", label: "Zombie Racing Club", imageURL: "zombie-racing-club.gif", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "the-visitors-airdrops", label: "The Visitors Airdrops", imageURL: "the-visitors-airdrops.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "eggnft", label: "EGGS NFT", imageURL: "eggnft.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "spacecats", label: "SpaceCats Metaverse Club", imageURL: "spacecats.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "riot-racers-racetrack-land", label: "Riot Racers Racetrack Land", imageURL: "riot-racers-racetrack-land.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "move-v4", label: "ArtistsCollide", imageURL: "move-v4.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "originative-cryptosharks", label: "CryptoSharks (SHARK)", imageURL: "originative-cryptosharks.gif", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "emoji-loot", label: "emoji-loot", imageURL: "emoji-loot.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "app-grow-house-growfarm", label: "GROW.HOUSE", imageURL: "app-grow-house-growfarm.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "oracle-shards-anrkey-x", label: "Oracle Shards AnRKey X", imageURL: "oracle-shards-anrkey-x.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "32x32x32", label: "32x32", imageURL: "32x32x32.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "doki-doki-matic", label: "Doki Doki Finance Polygon", imageURL: "doki-doki-matic.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "trumpchick", label: "LoserChick-TrumpChick", imageURL: "trumpchick.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "acid-dragons-nft", label: "Acid Dragons", imageURL: "acid-dragons-nft.gif", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "blokpax-fraxionals", label: "Blokpax Fraxionals", imageURL: "blokpax-fraxionals.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "rovi-transporter", label: "Rovi Transporter", imageURL: "rovi-transporter.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "loot-for-spark-era-lse", label: "Loot for Spark Era", imageURL: "loot-for-spark-era-lse.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "the-booze-club", label: "The Booze Club", imageURL: "the-booze-club.gif", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "non-fungible-matic", label: "Non-Fungible Matic", imageURL: "nonfungiblematic.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "cometh-spaceships", label: "Cometh Spaceships", imageURL: "cometh-spaceships.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "flowers", label: "Flowerpatch", imageURL: "flowers.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "bosschick", label: "LoserChick-BossChick", imageURL: "bosschick.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "loot-matic", label: "Loot - Matic", imageURL: "loot-matic.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "ioi-traderacemanager", label: "IOI | TradeRaceManager", imageURL: "ioi-traderacemanager.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "robotos-genesis", label: "Robotos Genesis", imageURL: "robotos-genesis.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "emojibotos", label: "Emojibotos", imageURL: "emojibotos.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "gravis-finance-captains-collection", label: "Gravis Finance Captains Collection", imageURL: "gravis-finance-captains-collection.gif", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "mycryptosaga", label: "MyCryptoSaga | Shin-cards", imageURL: "mycryptosaga.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "clucoin", label: "CluCoin", imageURL: "clucoin.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "beta-simba-x", label: "BETA_Simba x", imageURL: "beta-simba-x.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "forge-polygon", label: "Forge Polygon", imageURL: "forge-polygon.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "npt-pieces", label: "NPT - Pieces", imageURL: "npt-pieces.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "brave-frontier-heroes", label: "Brave Frontier Heroes", imageURL: "brave-frontier-heroes.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "dogecolors", label: "dogecolors", imageURL: "dogecolors.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "cryptoburbs", label: "CryptoBurbs", imageURL: "cryptoburbs.gif", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "moe-girls-arts", label: "Moe Girls Arts", imageURL: "moe-girls-arts.gif", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "league-of-kingdoms-item-v2", label: "League of Kingdoms (Polygon)", imageURL: "league-of-kingdoms-item-v2.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "polydoge-x-polycat", label: "PolyDoge X Polycat", imageURL: "polydoge-x-polycat.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "10000pixels", label: "10,000 Pixels", imageURL: "10000pixels.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "ethlings", label: "Ethlings", imageURL: "ethlings.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "psycho-teddybears", label: "Psycho Teddy Bearz", imageURL: "psycho-teddybears.gif", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "non-fungible-matic-v2-v2", label: "Non-Fungible Matic V2 V2", imageURL: "nonfungiblematic.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "boredaperound21basketball", label: "BAYC x round21 Basketball", imageURL: "boredaperound21basketball.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "chumbi-valley-founders-collection", label: "Chumbi Valley Founders Collection", imageURL: "chumbi-valley-founders-collection.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  // {name: "unidentified-contract-tyjqonyi6h", label: "unidentified-contract-tyjqonyi6h", imageURL: "unidentified-contract-tyjqonyi6h.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea},
  { name: "mfrstnft", label: "MfrstNFT", imageURL: "mfrstnft.gif", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "playdapp-dragon", label: "PLAYDAPP DRAGON", imageURL: "playdapp-dragon.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "36fuji-collectibles", label: "36FUJI Collectibles", imageURL: "36fuji-collectibles.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "moojis", label: "Moojis", imageURL: "moojis.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "realoot-1", label: "reaLoot", imageURL: "realoot-1.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "pebble-and-friends", label: "Pebble & Friends", imageURL: "pebble-and-friends.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "rabbitholegg", label: "Rabbithole_gg", imageURL: "rabbitholegg.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "f473-cards", label: "F473 Cards", imageURL: "f473-cards.gif", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "vinyl-cubos", label: "Vinyl-Cubos", imageURL: "vinyl-cubos.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "turtle-time", label: "Turtle Time", imageURL: "turtle-time.gif", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "polydoge-cards", label: "PolyDoge Cards", imageURL: "polydoge-cards.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "polypudgypenguins", label: "PolyPudgyPenguins", imageURL: "polypudgypenguins.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "polydoge-x-quickswap", label: "PolyDoge X QuickSwap", imageURL: "polydoge-x-quickswap.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "projectpigeon", label: "Project Pigeon", imageURL: "projectpigeon.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "showtime-genesis", label: "Showtime Genesis Drop", imageURL: "showtime-genesis.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "drakons-matic", label: "Drakons (Polygon)", imageURL: "drakons-matic.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "jpeg-partners-secret-invites", label: "JPEG Partners Secret Invites", imageURL: "jpeg-partners-secret-invites.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "gutter-art", label: "Gutter Art", imageURL: "gutter-art.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "laborchick", label: "LoserChick-LaborChick", imageURL: "laborchick.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "gradeapetroop", label: "GRADE APE TROOP", imageURL: "gradeapetroop.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "thewickedcraniums-x-popwonder", label: "The Wicked Craniums X Pop Wonder", imageURL: "thewickedcraniums-x-popwonder.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "oort-heroes", label: "Oort Heroes", imageURL: "oort-heroes.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "dinox-dnxi", label: "DinoX World - DNXI", imageURL: "dinox-dnxi.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "eggryptomonster-1", label: "EGGRYPTO Monsters", imageURL: "eggryptomonster-1.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "matic-monkey", label: "Matic Monkey", imageURL: "matic-monkey.gif", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "meebmaster-com-nft", label: "MeebMaster.com NFT", imageURL: "meebmaster-com-nft.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "diamond-rush-game", label: "DIAMOND RUSH GAME", imageURL: "diamond-rush-game.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "ichiyaduke23-v2", label: "ichiyaduke23 V2", imageURL: "ichiyaduke23-v2.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "bitskulls", label: "BitSkulls", imageURL: "bitskulls.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "furucombo-nft-v2", label: "Furucombo NFT V2", imageURL: "furucombo-nft-v2.png", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  { name: "gang-goods", label: "Gang Goods", imageURL: "gang-goods.gif", blockChain: BlockchainType.Polygon, platform: PlatformType.Opensea },
  // KLAYTN
  {name: "dogesoundclub-mates", label: "DOGESOUNDCLUB MATES", imageURL: "dogesoundclubmates.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "krafterspace", label: "krafterspace", imageURL: "krafterspace.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "theklaytnpunks", label: "KlaytnPunks", imageURL: "theklaytnpunks.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "klaydogesfriends", label: "KlayDogesFriend", imageURL: "klaydogesfriends.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "klayrock", label: "KLAYRock", imageURL: "klayrock.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "animalspunks-v2", label: "AnimalsPunks V2", imageURL: "animalspunks-v2.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "cases-by-kate", label: "Cases by Kate", imageURL: "cases-by-kate.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "klayanimalmix-v2", label: "KlayAnimalMix V2", imageURL: "klayanimalmix-v2.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "kckckckc2", label: "- - 8Es2kVo30z", imageURL: "kckckckc2.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "klaygems", label: "KlayGems", imageURL: "klaygems.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "the-klaytn-punks", label: "THE KLAYTN PUNKS", imageURL: "the-klaytn-punks.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "klaymonsterdressup", label: "KlayMonsterDressUp", imageURL: "klaymonsterdressup.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "space-travelers-stamps-v2", label: "Space travelers stamps V2", imageURL: "space-travelers-stamps-v2.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "projectwith", label: "ProjectWITH", imageURL: "projectwith.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "klayraccoonman", label: "KlayRaccoonMan", imageURL: "klayraccoonman.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "monsterium", label: "Monsterium", imageURL: "monsterium.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "klay-pengowl", label: "Klay Penguin and Owl", imageURL: "klay-pengowl.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "doggy-stamps", label: "Doggy Stamps", imageURL: "doggy-stamps.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "grumpy-old-pets", label: "Grumpy Old Pets", imageURL: "grumpy-old-pets.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "monster-flash", label: "Monster Flash", imageURL: "monster-flash.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "cute-cats-friends", label: "Cute cats & friends", imageURL: "cute-cats-friends.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "crazy-crypto-sheep-v2", label: "Crazy Crypto Sheep V2", imageURL: "crazy-crypto-sheep-v2.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "five-stars", label: "Five Stars", imageURL: "fivestars.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "lilis-pixel-art-gallery", label: "Lilis pixel art gallery", imageURL: "lilis-pixel-art-gallery.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "klayclam", label: "KLAYClam", imageURL: "klayclam.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "dancers-gtgaqutqe4", label: "Dancers memories", imageURL: "dancers-gtgaqutqe4.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "klaychicken", label: "KlayChicken", imageURL: "klaychicken.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "projectwith-event", label: "ProjectWITH EVENT", imageURL: "projectwith-event.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "tessa-card", label: "Tessa Card", imageURL: "tessa-card.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "angel-league-nft-v2", label: "angel-league-nft-v2", imageURL: "angel-league-nft-v2.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "klaymojis", label: "KlayMojis", imageURL: "klaymojis.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "honor-of-kingdoms", label: "Honor of Kingdoms", imageURL: "honorofkingdoms.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "klip", label: "Klip", imageURL: "klip.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "cryptodragons-klatyn", label: "CryptoDragons", imageURL: "cryptodragons-klatyn.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "spells-of-genesis-firstoasis-card-klaytn", label: "Spells of Genesis FirstOasis Card", imageURL: "spells-of-genesis-firstoasis-card-klaytn.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "inconvenience-rank", label: "Inconvenience Rank", imageURL: "inconvenience-rank.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "cryptocarto-pintoken", label: "CryptoCarto PinToken", imageURL: "cryptocarto-pintoken.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "princess-maker-card", label: "Princess Maker Card", imageURL: "princess-maker-card.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "klip-poca", label: "Klip POCA", imageURL: "klip-poca.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "angelleague-nft", label: "Angel League NFT", imageURL: "angelleague-nft.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "blocknation-xyz-land-token", label: "BlockNation.XYZ", imageURL: "blocknation-xyz-land-token.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "hyundai-card-nft", label: "Hyundai Card NFT", imageURL: "hyundai-card-nft.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "blue-storage-card", label: "Blue Storage Card", imageURL: "blue-storage-card.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "quotabook-securities-authentication", label: "Quotabook Securities Authentication", imageURL: "quotabook-securities-authentication.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "somesing-card", label: "Somesing Card", imageURL: "somesing-card.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "screena", label: "Screena", imageURL: "screena.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "linka-nft-card", label: "LINKA NFT Card", imageURL: "linka-nft-card.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "jeju-blockchain-hackathon-card", label: "Jeju Blockchain Hackathon Card", imageURL: "jeju-blockchain-hackathon-card.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "crypto-character-card", label: "Crypto Character Card", imageURL: "crypto-character-card.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "pedal-bicycle-card", label: "Pedal Bicycle Card", imageURL: "pedal-bicycle-card.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "treasurer", label: "treasurer", imageURL: "treasurer.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "cengold", label: "cengold", imageURL: "cengold.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "ikol", label: "ikol", imageURL: "ikol.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "league-of-kingdoms-invite", label: "league-of-kingdoms-invite", imageURL: "league-of-kingdoms-invite.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "league-of-kingdoms-v3", label: "league-of-kingdoms-v3", imageURL: "league-of-kingdoms-v3.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "klaytn-nft-studio", label: "klaytn-nft-studio", imageURL: "klaytn-nft-studio.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "klaylion", label: "klaylion", imageURL: "klaylion.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "kind-nxt-member", label: "kind-nxt-member", imageURL: "kind-nxt-member.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "snu", label: "snu", imageURL: "snu.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "3space-art", label: "3space-art", imageURL: "3space-art.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "kns", label: "kns", imageURL: "kns.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "syt", label: "syt", imageURL: "syt.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "nft-open-market", label: "nft-open-market", imageURL: "nft-open-market.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "ground-x-nft", label: "ground-x-nft", imageURL: "ground-x-nft.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "mytemsnft17", label: "mytemsnft17", imageURL: "mytemsnft17.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "cowcow-nft", label: "cowcow-nft", imageURL: "cowcow-nft.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "universe-photo-card", label: "universe-photo-card", imageURL: "universe-photo-card.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "frogonc", label: "frogonc", imageURL: "frogonc.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "testcard", label: "testcard", imageURL: "testcard.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "krafterspacenfts", label: "krafterspacenfts", imageURL: "krafterspacenfts.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "orbit-bridge-klaytn-nft", label: "orbit-bridge-klaytn-nft", imageURL: "orbit-bridge-klaytn-nft.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "legal-limpidity-contract", label: "legal-limpidity-contract", imageURL: "legal-limpidity-contract.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "pizza-nft-1", label: "pizza-nft-1", imageURL: "pizza-nft-1.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "bitarte-v2", label: "bitarte-v2", imageURL: "bitarte-v2.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "klayjw", label: "klayjw", imageURL: "klayjw.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "klayjune", label: "klayjune", imageURL: "klayjune.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "duddlf", label: "duddlf", imageURL: "duddlf.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "businesscard", label: "businesscard", imageURL: "businesscard.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "klaylion-v3", label: "klaylion-v3", imageURL: "klaylion-v3.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "crystal-collection-klaytn", label: "crystal-collection-klaytn", imageURL: "crystal-collection-klaytn.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "grt-v2", label: "grt-v2", imageURL: "grt-v2.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "mystarpick", label: "mystarpick", imageURL: "mystarpick.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "try-fsrufawklc", label: "try-fsrufawklc", imageURL: "try-fsrufawklc.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "klaylion-v2", label: "klaylion-v2", imageURL: "klaylion-v2.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "afk-battleidle-princess-card", label: "afk-battleidle-princess-card", imageURL: "afk-battleidle-princess-card.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "nftt", label: "nftt", imageURL: "nftt.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "konnect-nft-certification", label: "konnect-nft-certification", imageURL: "konnect-nft-certification.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "ulmaya", label: "ulmaya", imageURL: "ulmaya.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "donation-certificate-card", label: "donation-certificate-card", imageURL: "donation-certificate-card.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "good-neighbors", label: "good-neighbors", imageURL: "good-neighbors.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "temconft", label: "temconft", imageURL: "temconft.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "knight-story-item-klatyn", label: "knight-story-item-klatyn", imageURL: "knight-story-item-klatyn.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  // {name: "n52-coupon", label: "n52-coupon", imageURL: "n52-coupon.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea},
  {name: "sword-magic-item", label: "Crypto Sword & Magic", imageURL: "swordmagic.png", blockChain: BlockchainType.Klaytn, platform: PlatformType.Opensea}
];
