export const VIEW_WALLET_NORMAL = 'VIEW_WALLET_NORMAL';
export const VIEW_WALLET_CONNECT_PRIVI = 'VIEW_WALLET_CONNECT_PRIVI';
export const VIEW_WALLET_SIGN_IN_ALERT = 'VIEW_WALLET_SIGN_IN_ALERT';
export const VIEW_WALLET_SIGNATURE_REQUEST = 'VIEW_WALLET_SIGNATURE_REQUEST';
export const VIEW_WALLET_CONNECT_SERVICE = 'VIEW_WALLET_CONNECT_SERVICE';

export const WALLET_CONNECT_PRIVI = 0;
export const WALLET_CONNECT_METAMASK = 1;
export const WALLET_CONNECT_SERVICE = 2;
