import { makeStyles } from "@material-ui/core/styles";

export const wallPostModalStyles = makeStyles(() => ({
  root: {
    width: '680px !important',
  },
  modalWallPostContent: {
    padding: 30,
  },
  modalWallPostContainer: {},
  closeButton: {
    display: "flex",
    justifyContent: "flex-end",
    cursor: "pointer",
  },
  paper: {
    width: 267,
    marginRight: -267,
    marginLeft: -90,
    borderRadius: 10,
    boxShadow: "0px 2px 20px rgba(0, 0, 0, 0.1)",
    position: "inherit",
  },
  dateOfPublished: {
    fontFamily: '"Agrandir", sans-serif',
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: 14,
    margin: "20px 0 8px",
    color: "#4f4f4f",
  },
  mainPhotoWallPost: {
    width: "50%",
    height: 200,
    backgroundColor: "grey",
    margin: "auto",
  },
  reactPlayer: {
    height: 180,
    borderRadius: 20,
    transform: "none",
    width: 180,
  },
  reactPlayerModal: {},
  imagesWallPost: {
    display: "flex",
    alignItems: "center",
    overflowX: "auto",
    scrollbarWidth: "none",
    padding: "15px 0",
    justifyContent: "space-between",
  },
  descriptionImageWallPost: {
    minWidth: 200,
    marginRight: 15,
    width: "50%",
    maxWidth: 455,
    height: 200,
  },
  firstPartWallPost: {
    display: "flex",
    flexWrap: "wrap",
  },
  hashtagsDate: {
    alignItems: "flex-end",
  },
  userProfileWallPost: {
    display: "flex",
    alignItems: "center",
    width: 420,
  },
  userCardWallPost: {
    display: "flex",
    alignItems: "center",
    width: 420,
    marginTop: 25,
  },
  userCardImageWallPost: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    width: "50px",
    height: "40px",
    minWidth: "40px",
    minHeight: "40px",
    marginLeft: "0",
  },
  authorPhotoWallPost: {
    width: 56,
    height: 56,
    backgroundColor: "grey",
    borderRadius: "50%",
    boxShadow: "0px 0px 8px 4px rgba(34, 60, 80, 0.2)",
    border: "2px solid #ffffff",
    cursor: "pointer",
  },
  userOnline: {
    background: "linear-gradient(97.4deg, #23d0c6 14.43%, #00cc8f 85.96%)",
    border: "2px solid #ffffff",
    boxSizing: "border-box",
    alignSelf: "flex-end",
    justifySelf: "flex-end",
    width: 12,
    height: 12,
    borderRadius: "50%",
    marginLeft: -15,
    marginBottom: 2.5,
    boxShadow: "0px 0px 8px 4px rgba(34, 60, 80, 0.2)",
  },
  authorNameWallPost: {
    fontSize: 18,
    fontWeight: 700,
    lineHeight: "24px",
    color: "#181818",
    paddingBottom: 4,
    cursor: "pointer",
  },
  authorInfoWallPost: {
    display: "flex",
  },
  authorSlugWallPost: {
    fontSize: 14,
    fontWeight: 700,
    background: "linear-gradient(97.4deg, #ff79d1 14.43%, #db00ff 79.45%)",
    "-webkit-background-clip": "text",
    "-webkit-text-fill-color": "transparent",
  },
  authorVerifiedWallPost: {
    "& img": {
      width: 16.5,
      height: 16.5,
    },
  },
  authorLevelWallPost: {
    marginLeft: 6.75,
    border: "1px solid #99a1b3",
    boxSizing: "border-box",
    borderRadius: 38.6667,
    width: 53,
    height: 18,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    "& span": {
      color: "#99a1b3",
      fontSize: 11,
      lineHeight: "1px",
    },
  },
  hashtags: {
    display: "flex",
    margin: 0,
  },
  hashtag: {
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: 14,
    lineHeight: "120%",
    display: "flex",
    alignItems: "center",
    textAlign: "center",
    color: "#707582",
    border: "1.42652px solid #707582",
    boxSizing: "border-box",
    borderRadius: 51.3548,
    padding: "4px 16px",
    marginRight: 10,
  },
  nameWallPost: {
    fontFamily: "Agrandir",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: 22,
    lineHeight: "104.5%",
    color: "#181818",
    marginTop: 38,
    marginBottom: 16,
  },
  textShort: {
    fontSize: 18,
    color: "#333333",
    fontFamily: "Agrandir",
    fontStyle: "normal",
    fontWeight: "normal",
    // fontSize: 14,
    lineHeight: "120%",
    // color: "#707582",
    marginTop: 0,
  },
  lastRowResponsesLikes: {
    display: "flex",
    width: "100%",
    justifyContent: "space-between",
    marginTop: 40,
    marginBottom: 22,
  },
  numResponsesWallPost: {
    display: "flex",
    alignItems: "center",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: 14,
    lineHeight: "104.5%",
    color: "#4f4f4f",
  },
  responsesIconWallPost: {
    width: 16,
    height: 16,
    marginRight: 8,
    fontWeight: 400,
    fontSize: 14,
    lineHeight: "20px",
    color: "rgb(101, 110, 126)",
  },
  socialsRowPostItem: {
    background: "#181818",
    border: "2px solid #ffffff",
    borderRadius: 18,
    width: 90,
    height: 32,
    display: "flex",
    justifyContent: "space-around",
    filter: "drop-shadow(0px 2px 8px rgba(0, 0, 0, 0.2))",
  },
  responsesWallPost: {
    paddingBottom: 20,
    paddingTop: 20,
  },
  addResponseWallPost: {
    width: "calc(100%)",
    height: 49,
    display: "flex",
    alignItems: "center",
    padding: 16,
    boxSizing: "border-box",
    border: "1px solid #e0e4f3",
    borderRadius: 8,
  },
  inputResponseWallPost: {
    fontsize: 14,
    fontWeight: 400,
    width: "100%",
    display: "flex",
    justifyContent: "flex-start",
  },
  textFieldResponseWallPost: {
    color: "rgb(101, 110, 126)",
    border: "none",
    width: "100%",
  },
  arrowRightBlueResponseWallPost: {
    display: "flex",
    justifyContent: "flex-end",
    cursor: "pointer",
  },
  arrowRightBlueWallPost: {
    width: 14,
    height: 14,
  },
  wrapperComments: {
    background: "#ffffff",
    boxShadow: "0px 2px 12px rgba(0, 0, 0, 0.1)",
    borderRadius: 20,
    marginBottom: 16,
  },
  responsesWallPostComponent: {
    paddingRight: 30,
    paddingLeft: 30,
    display: "flex",
  },
  firstRowResponseWallPost: {
    display: "flex",
    width: "30%",
    maxWidth: 200,
    alignItems: "center",
    paddingTop: 20,
    paddingBottom: 20,
  },
  leftColResponseWallPostComments: {
    paddingRight: 24,
    width: "100%",
    borderRight: "1px solid #99a1b3",
  },
  authorNameWallPostComments: {
    fontSize: 18,
    paddingBottom: 2,
    cursor: "pointer",
  },
  labelResponseWallPost: {
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: 14,
    lineHeight: "120%",
    color: "#707582",
    paddingBottom: 0,
    display: "flex",
    width: "100%",
    flexDirection: "column",
    justifyContent: "center",
    paddingLeft: 24,
  },
  labelWrapperResponseWallPost: {
    display: "block",
    marginRight: "auto",
  },
  rightColResponseWallPostComment: {
    display: "block",
    marginLeft: "auto",
    textAlign: "right",
  },
}));
