import { makeStyles } from "@material-ui/core/styles";

export const landStyles = makeStyles(theme => ({
  container: {
    background: "#9EACF2",
    width: "100%",
    height: "100vh",
    overflowY: "auto",
    fontFamily: "Monument Extended",
  },
  content: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    padding: theme.spacing(5),
    alignItems: "center",
    justifyContent: "flex-start",
    color: "#431AB7",
    minHeight: "100vh",
    overflow: "hidden",
    [theme.breakpoints.down("xs")]: {
      padding: `${theme.spacing(3)}px ${theme.spacing(2)}px`,
    },
    "& div": {
      zIndex: 1,
    },
  },
  yellowBox: {
    background: "#DDFF57",
    borderRadius: theme.spacing(1),
    boxShadow: "0px 4px 4px #431AB7",
    padding: theme.spacing(1),
  },
  img1: {
    width: theme.spacing(30),
    height: theme.spacing(30),
    position: "absolute",
    left: "-5%",
    top: "5%",
    [theme.breakpoints.down("xs")]: {
      width: theme.spacing(15),
      height: theme.spacing(15),
      left: "-13%",
    },
  },
  img2: {
    width: theme.spacing(15),
    height: theme.spacing(15),
    position: "absolute",
    left: "4%",
    top: "15%",
    [theme.breakpoints.down("xs")]: {
      width: theme.spacing(7),
      height: theme.spacing(7),
      left: "3%",
      top: "12%",
    },
  },
  img3: {
    width: theme.spacing(30),
    height: theme.spacing(30),
    position: "absolute",
    right: "-5%",
    top: "20%",
    [theme.breakpoints.down("xs")]: {
      width: theme.spacing(15),
      height: theme.spacing(15),
      right: "-15%",
      top: "0%",
    },
  },
  img4: {
    width: theme.spacing(10),
    height: theme.spacing(10),
    position: "absolute",
    left: "2%",
    top: "50%",
    [theme.breakpoints.down("xs")]: {
      width: theme.spacing(5),
      height: theme.spacing(5),
      left: "4%",
      top: "30%",
    },
  },
  img5: {
    width: theme.spacing(7),
    height: theme.spacing(7),
    position: "absolute",
    left: "4%",
    top: "70%",
    [theme.breakpoints.down("xs")]: {
      width: theme.spacing(3.5),
      height: theme.spacing(3.5),
      left: "8%",
      top: "35%",
    },
  },
  img6: {
    width: theme.spacing(20),
    height: theme.spacing(20),
    position: "absolute",
    left: "60%",
    top: "35%",
    [theme.breakpoints.down("xs")]: {
      width: theme.spacing(10),
      height: theme.spacing(10),
      left: "70%",
      top: "30%",
    },
  },
  img7: {
    width: theme.spacing(5),
    height: theme.spacing(5),
    position: "absolute",
    left: "70%",
    top: "45%",
    [theme.breakpoints.down("xs")]: {
      width: theme.spacing(2.5),
      height: theme.spacing(2.5),
      left: "20%",
      top: "70%",
    },
  },
  img8: {
    width: theme.spacing(15),
    height: theme.spacing(15),
    position: "absolute",
    right: "2%",
    top: "75%",
    [theme.breakpoints.down("xs")]: {
      width: theme.spacing(7),
      height: theme.spacing(7),
      left: "70%",
      top: "80%",
    },
  },
  img9: {
    width: theme.spacing(30),
    height: theme.spacing(30),
    position: "absolute",
    left: "4%",
    bottom: "-15%",
    [theme.breakpoints.down("xs")]: {
      width: theme.spacing(15),
      height: theme.spacing(15),
      left: "15%",
      bottom: "5%",
    },
  },
  img10: {
    width: theme.spacing(10),
    height: theme.spacing(10),
    position: "absolute",
    left: "65%",
    bottom: "5%",
    [theme.breakpoints.down("xs")]: {
      width: theme.spacing(5),
      height: theme.spacing(5),
      left: "70%",
      bottom: "30%",
    },
  },
  img11: {
    width: theme.spacing(15),
    height: theme.spacing(15),
    position: "absolute",
    left: "70%",
    bottom: "10%",
    [theme.breakpoints.down("xs")]: {
      width: theme.spacing(7),
      height: theme.spacing(7),
      left: "65%",
      bottom: "22%",
    },
  },
  starImg: {
    [theme.breakpoints.down("xs")]: {
      width: theme.spacing(2),
    },
  },
  headerBox: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    [theme.breakpoints.down("sm")]: {
      flexDirection: "column",
    },
  },
  title: {
    fontSize: 56,
    fontWeight: 400,
    textTransform: "uppercase",
    [theme.breakpoints.down("xs")]: {
      fontSize: 24,
    },
  },
  header1: {
    fontSize: 32,
    fontWeight: 400,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    [theme.breakpoints.down("xs")]: {
      fontSize: 18,
    },
  },
  header2: {
    fontSize: 24,
    fontWeight: 400,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    [theme.breakpoints.down("xs")]: {
      fontSize: 14,
    },
  },
  header3: {
    fontSize: 20,
    fontWeight: 400,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    [theme.breakpoints.down("xs")]: {
      fontSize: 12,
    },
  },
  header4: {
    fontSize: 16,
    fontWeight: 400,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    [theme.breakpoints.down("xs")]: {
      fontSize: 12,
    },
  },
  inputBox: {
    background: "#E0E5FB",
    boxShadow: "0px 4px 4px rgba(255, 255, 255, 0.2), inset 0px 4px 4px #919FE3",
    minWidth: theme.spacing(70),
    padding: `${theme.spacing(1)}px ${theme.spacing(1)}px`,
    borderRadius: theme.spacing(1),
    fontFamily: "Monument Extended",
    fontSize: 12,
    fontWeight: 400,
    "& input": {
      textAlign: "center",
      color: "#431AB7",
      fontFamily: "Monument Extended",
      "&::placeholder": {
        color: "#9EACF2",
        opacity: 1,
      },
    },
    "&::placeholder": {
      color: "#9EACF2",
    },
    [theme.breakpoints.down("xs")]: {
      minWidth: 0,
      width: "100%",
      marginLeft: theme.spacing(2),
      marginRight: theme.spacing(2),
    },
  },
  staticBox: {
    background: "#9EACF2",
    boxShadow: "0px 4px 4px rgba(255, 255, 255, 0.2), inset 0px 4px 4px #919FE3",
    padding: `${theme.spacing(1)}px ${theme.spacing(2)}px`,
    borderRadius: theme.spacing(1),
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
}));
