import { makeStyles } from "@material-ui/core/styles";

export const normalNFTCardStyles = makeStyles(theme => ({
  card: {
    background: "#DDFF57",
    backdropFilter: "blur(4.82073px)",
    borderRadius: 11.3,
    clipPath: "polygon(100% 0%, 100% 80%,  50% 91%, 0% 80%, 0% 0%)",
    padding: 8,
    height: 516,
    width: "100%",
    cursor: "pointer",
  },
  innerBox: {
    background: "#9EACF2",
    boxShadow: "0px 1.67251px 1.67251px rgba(0, 0, 0, 0.03)",
    borderRadius: 11.3,
    clipPath: "polygon(100% 0%, 100% 80%,  50% 90%, 0% 80%, 0% 0%)",
    padding: 16,
    height: 500,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    color: "#fff",
    "& img": {
      width: "100%",
      height: 250,
    },
    [theme.breakpoints.between(960, 980)]: {
      padding: 12,
    },
  },
  starGroup: {
    display: "flex",
    alignItems: "center",
  },
  ntfName: {
    fontSize: 16,
    fontWeight: 800,
    fontFamily: "Agrandir",
    lineHeight: "21px",
    textTransform: "capitalize",
    marginBottom: 8,
  },
  priceSection: {
    display: "flex",
    alignItems: "center",
    fontSize: 16,
    fontWeight: 800,
    fontFamily: "Agrandir",
    lineHeight: "21px",
    letterSpacing: "0.02em",
    marginTop: 16,
  },
  volumnSection: {
    display: "flex",
    alignItems: "center",
    fontSize: 14,
    fontWeight: 800,
    fontFamily: "Agrandir",
    lineHeight: "18px",
    letterSpacing: "0.02em",
    textTransform: "uppercase",
    marginTop: 8,
  },
  shadow: {
    width: 40,
    height: 5.25,
    background: "#431AB7",
    opacity: 0.2,
    filter: "blur(2.9269px)",
    marginTop: -24,
  },
  liveTradingLabel: {
    display: "flex",
    height: 26,
    padding: "5px 11px",
    color: "#431AB7",
    fontSize: 11,
    fontWeight: 800,
    fontFamily: "Agrandir",
    lineHeight: "14px",
    borderRadius: 8,
    border: "1px solid #431AB7",
    "& span": {
      marginLeft: 4.7,
    },
  },
  liveFundingLabel: {
    display: "flex",
    height: 26,
    padding: "5px 11px",
    color: "#DDFF57",
    fontSize: 11,
    fontWeight: 800,
    fontFamily: "Agrandir",
    lineHeight: "14px",
    borderRadius: 8,
    border: "1px solid #DDFF57",
    "& span": {
      marginLeft: 4.7,
    },
  },
}));
