import { makeStyles } from "@material-ui/core/styles";

export const mediaCardStyles = makeStyles(theme => ({
  container: {
    background: "#ffffff",
    boxShadow: "0px 4px 8px #9EACF2",
    borderRadius: 16,
    cursor: "pointer",
    minWidth: 276,
    height: "fit-content",
    padding: "0px 16px 16px",
    position: "relative",
  },
  header: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    justifyContent: "space-between",
    position: "absolute",
    padding: "16px",
    left: 0,
  },
  imageContainer: {
    width: "calc(100% + 16px * 2)",
    marginLeft: "-16px",
    borderRadius: "16px 16px 0px 0px",
    height: "174px",
    "& img": {
      borderRadius: "16px 16px 0px 0px",
      height: "174px",
      width: "100%",
    },
  },
  primaryBtn: {
    background: "#DDFF57 !important",
    color: "#431AB7 !important",
  },
  avatar: {
    backgroundColor: "#c4c4c4",
    width: 32,
    minWidth: 32,
    height: 32,
    border: "2px solid #FFFFFF",
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
    backgroundPosition: "center",
    borderRadius: "50%",
  },
  black: {
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: 14,
    lineHeight: "120%",
    color: "#1a1b1c",
  },
  creatorName: {
    maxWidth: 124,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    lineHeight: 1.2,
  },
  gray: {
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: 14,
    lineHeight: "120%",
    color: "#a4a4a4",
    overflow: "hidden",
    "& span": {
      fontStyle: "normal",
      fontWeight: 800,
      fontSize: 18,
      lineHeight: "104.5%",
      color: "#431ab7",
      marginLeft: 8,
    },
  },
  fruitsContainer: {
    "& > div > div": {
      background: "#9EACF2",
      width: 30,
      height: 30,
      borderRadius: 15,
      padding: 5,
      filter: "dropShadow(0px 1.5px 6px rgba(0, 0, 0, 0.2))",
      "& img": {
        width: 21,
      },
    },
  },
  fractionBox: {
    fontWeight: 800,
    fontSize: "11px",
    lineHeight: "104.5%",
    color: "#FFFFFF",
    padding: "9px 14px",
    background: "#9EACF2",
    borderRadius: "36px",
    width: "fit-content",
  },
  title: {
    fontStyle: "normal",
    fontWeight: 800,
    fontSize: "18px",
    lineHeight: "104.5%",
    color: "#081831",
  },
  desc: {
    marginTop: "16px",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "14px",
    lineHeight: "140%",
    color: "#A4A4A4",
  },
  flexBox: {
    display: "flex",
    alignItems: "center",
  },
  header1: {
    fontSize: "14px",
    color: "#A4A4A4",
  },
  header2: {
    fontSize: "20px",
    color: "#1A1B1C",
  },
  header3: {
    fontStyle: "normal",
    fontWeight: 800,
    fontSize: "18px",
    lineHeight: "120%",
    color: "#081831",
    textShadow: "2px 2px 12px rgba(0, 0, 0, 0.1)",
  },
  title1: {
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "16px",
    lineHeight: "120%",
    color: "#A4A4A4",
    textShadow: "2px 2px 12px rgba(0, 0, 0, 0.1)",
  },
  content1: {
    fontStyle: "normal",
    fontWeight: 800,
    fontSize: "18px",
    lineHeight: "120%",
    color: "#081831",
    textShadow: "2px 2px 12px rgba(0, 0, 0, 0.1)",
  },
  moreBox: {
    marginLeft: -theme.spacing(2),
    background: "white",
    borderRadius: theme.spacing(2),
    boxShadow: "0px 2px 4px rgba(0, 0, 0, 0.25)",
    padding: `${theme.spacing(0.5)}px ${theme.spacing(1)}px`,
  },
  typeBox: {
    display: "flex",
    alignItems: "center",
    background: "white",
    borderRadius: theme.spacing(2),
    boxShadow: "0px 2px 4px rgba(0, 0, 0, 0.25)",
    padding: `${theme.spacing(0.5)}px ${theme.spacing(1)}px`,

    "& img": {
      width: "20px",
    },
  },
  radialLabelBox: {
    width: theme.spacing(3),
    height: theme.spacing(3),
    borderRadius: theme.spacing(1),
    fontSize: "14px",
  },
  menuBox: {
    background: "#FFFFFF",
    borderRadius: "18px",
    height: 30,
    width: 30,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    "& img": {
      height: 3,
      transform: "rotate(90deg)",
    },
  },
  table: {
    "& .MuiTableContainer-root": {
      boxShadow: "none",
      "& .MuiTableRow-root.MuiTableRow-head": {
        backgroundColor: "transparent",
      },
      ".MuiTableCell-root": {
        borderBottom: "none",
      },
    },
  },
  button: {
    backgroundColor: "#DDFF57 !important",
    color: "#431AB7 !important",
    fontSize: "18px !important",
  },
  tableAccordion: {
    "& *": {
      fontFamily: "Agrandir",
      fontSize: "14px",
    },
    "& .MuiTableContainer-root": {
      borderRadius: 16,
      "& .MuiTableRow-root.MuiTableRow-head": {
        backgroundColor: "#9EACF2",
        "& .MuiTableCell-root.MuiTableCell-head": {
          color: "#DDFF57",
          textTransform: "none",
        },
      },
    },
  },
}));
