import { makeStyles } from "@material-ui/core";

export const claimPodModalStyles = makeStyles(() => ({
  modal: {
    width: "458px !important",
    padding: "26px 40px !important",
    maxHeight: "85vh !important",
    maxWidth: "85vw !important",
    alignSelf: "center",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    background: "#EAE8FA !important",
    boxShadow: "0px 2px 14px rgba(0, 0, 0, 0.08)",
    borderRadius: 14,
  },
  modalContent: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
    "& img": {
      width: "50px",
      height: "50px",
      margin: "45px 0px 30px",
    },
    "& h3": {
      margin: "0px",
      color: "#2D3047",
      fontWeight: 600,
      fontSize: "18px",
    },
    "& h5": {
      margin: "18.5px 0px 30px",
      color: "#54658F",
      fontWeight: 500,
      fontSize: "16px",
      lineHeight: "19px",
    },
  },
  artistList: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    borderTop: "1px solid #17171736",
    borderBottom: "1px solid #17171736",
    marginBottom: "32px",
  },
  artistTile: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    padding: "2px 0px",
    borderBottom: "1px dashed #17171736",
    "& span": {
      fontSize: "14px",
      fontWeight: 700,
      color: "#181818",
    },
    "&:last-child": {
      borderBottom: "none",
    },
  },
  artistImage: {
    border: "2px solid #FFFFFF",
    marginRight: "10px",
    width: "48px",
    height: "48px",
    minWidth: "48px",
    borderRadius: "24px",
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundColor: "white",
  },
  label: {
    color: "#181818",
    fontSize: "18px",
    marginBottom: "8px",
    width: "100%",
    maxWidth: 370,
    "& first-child": {
      marginTop: "20px",
    },
  },
  input: {
    padding: "12px 18px",
    background: "#F7F9FE",
    border: "1px solid #E0E4F3",
    boxSizing: "border-box",
    borderRadius: "6px",
    marginBottom: "27px",
    width: "100%",
    color: "#707582",
  },
  description: {
    color: " #707582 !important",
    textAlign: "center",
    maxWidth: 300,
  },
  flexBox: {
    display: "flex",
    alignItems: "center",
  },
  toConnectButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 10,
    padding: 15,
    height: 54,
    cursor: "pointer",
  },
  instagramButton: {
    display: "none",
  },
}));
