import { makeStyles } from "@material-ui/core/styles";
import { Gradient } from "shared/ui-kit";

export const perkCardStyles = makeStyles(theme => ({
  card: {
    display: "flex",
    alignItems: "center",
    flexDirection: "column",
    justifyContent: "center",
    width: "100%",
    minWidth: 260,
    borderRadius: 16,
    position: "relative",
  },
  topActions: {
    marginBottom: -60,
    display: "flex",
    zIndex: 3,
    width: "100%",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    "& img": {
      marginRight: 6,
      height: 20,
      cursor: "pointer",
    },
  },
  trending: {
    color: "black",
    fontWeight: 800,
    fontSize: 14.5,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    padding: "7px 14px 6px",
    background: Gradient.Green,
    borderRadius: 36,
  },
  header: {
    display: "flex",
    alignItems: "center",
    flexDirection: "column",
    justifyContent: "center",
    width: "100%",
    minWidth: 193,
    borderTopRightRadius: 16,
    borderTopLeftRadius: 16,
    position: "relative",
  },
  aspectRatioWrapper: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    overflow: "hidden",
    "&:last-child": {
      transition: "all 0.3s ease",
    },
  },
  image: {
    borderTopRightRadius: 16,
    borderTopLeftRadius: 16,
    marginBottom: -8,
    width: "100%",
    height: "100%",
    background: "linear-gradient(93.41deg, rgba(0, 255, 21, 0.3) 33.32%, rgba(177, 255, 0, 0.3) 66.18%)",
  },
  img: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  hidden: {
    width: 0,
    opacity: 0,
    minWidth: 0,
  },
  content: {
    fontSize: 18,
    borderTopRightRadius: 16,
    borderTopLeftRadius: 16,
    flex: 1,
    borderTop: "none",
    padding: "60px 16px 16px",
    position: "relative",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: "100%",
    color: "white",
    background: "hsl(0, 0%, 0%, 0.8)",
  },
  bottomContent: {
    width: "100%",
    padding: 16,
    boxShadow: "0px 2px 8px rgba(0, 0, 0, 0.12)",
    borderBottomRightRadius: 16,
    borderBottomLeftRadius: 16,
    background: "#eff2f8",
  },
}));
